server:
  port: 8080

# MySQL #
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: chenmixuexi1
    url: jdbc:mysql://localhost:3306/springdemo?useUnicode=true&characterEncoding=Utf-8
  application:
    name: springTestDemo

# MYBATIS #
mybatis:
  type-aliases-package: com.example.demo.mybatis.entity

# SPRING-DOC #
springdoc:
  swagger-ui:
    display-request-duration: true
    operations-sorter: method
    disable-swagger-default-url: true
    use-root-path: true